### ISSUE TITLE
Feature suggestion for Gun Bonsai: Autoautosave integration

### ISSUE THREAD

**Issue by mmaulwurff** [ToxicFrog/doom-mods#1]
Proposal: trigger an [Autoautosave](https://github.com/mmaulwurff/autoautosave/) when a weapon levels up.

AAS has integration mechanism that makes this easy. Create an actor which name starts with `aas_instant_` and spawn that actor when the level up happens. This actor may be immediately destroyed. Example of such actor:
```
class aas_instant_Bonsai : Actor
{
  States
  {
  Spawn:
    TNT1 A 0;
    stop;
  }
}
```

Spawning such actor triggers "Important item is found" event. The event name doesn't 100% correspond to a level up event, but I think it would be sufficient.

Edit: note that this integration doesn't create a dependency on AAS.

**Comment by ToxicFrog** [comment]
That looks pleasingly straightforward to implement. Does it need a toggle, or does AAS keep multiple autosaves? I worry a bit about the situation where someone gets a level-up in the middle of a tense fight right before they take a cyberdemon rocket to the face and die.

Alternately, I could have it trigger not when the actual level-up occurs but just before (or after) they choose the upgrade.

**Comment by mmaulwurff** [comment]
AAS keeps as many autosaves as it's configured in GZDoom, typically multiple, I think.

You are right, the described problem exists with any AAS autosaves. A toggle would be nice, because AAS integration will trigger a generic save event, and a user may want to disable save on upgrade, but keep the generic one for other purposes.

Triggering when the user chooses the upgrade can be done even without modification on Gun Bonsai side, with an add-on, by reacting to `bonsai_choose_level_up_option` netevent. One user asked if AAS could save particularly on the leveling up.

**Comment by ToxicFrog** [comment]
It sounds like the most flexible option is just to have GB also emit a `bonsai_weapon_level_up` netevent at the moment the level-up happens, and then AAS users can just tell it to autosave when that event fires.

**Comment by mmaulwurff** [comment]
Okay, when GB emits `bonsai_weapon_level_up`, I'll add a reaction to it to AAS.

**Comment by ToxicFrog** [comment]
0.9.1 was just released. It sends `bonsai-level-up` when the level is earned and `bonsai-choose-level-up-option` when an upgrade is claimed (or the level is rejected). For compatibility with existing configs it also sends `bonsai_choose_level_up_option` still; this will be removed in a later version.
