### ISSUE TITLE
Crash when using weapon with thunderbolt lvl 2

### ISSUE THREAD

**Issue by pbates5** [ToxicFrog/doom-mods#12]
Received this error:

![Screenshot_20221224-094415304](https://user-images.githubusercontent.com/96102386/209449301-d050abe2-7b14-4ddb-929f-9138d98e0b0a.jpg)

**Comment by ToxicFrog** [comment]
This *might* be fixed in [0.9.7](https://github.com/ToxicFrog/doom-mods/releases/tag/gun-bonsai-0.9.7), which reworks the Thunderbolt VFX to use sprites -- please try it out and let me know.

**Comment by ToxicFrog** [comment]
And if not it might be fixed in 527de5f97b177c7932b98f6a78544f58d5ec9cf9 which will be released in 0.9.8.
