### ISSUE TITLE
Crash when accessing player level up menu in Gun Bonsai 0.9.6

### ISSUE THREAD

**Issue by pbates5** [ToxicFrog/doom-mods#13]
Sorry to burden you again with another bug but I'm now having issues with the newest release of Gun Bonsai. Whenever I get enough weapon level ups to level up the player my game crashes when it tries to bring up the player menu. I should mention I have the GB options set to display all available upgrade options upon level up. This is a screenshot from the first time it happened:
![Screenshot_20221230-103741950](https://user-images.githubusercontent.com/96102386/210111606-d37d3231-5d27-42cc-941a-5d20e10c552e.jpg)

**Comment by ToxicFrog** [comment]
This is an issue where some builds of gzdoom will crash on division by zero, and some (like the one I test on!) are fine with it. This should be fixed in [release 0.9.7](https://github.com/ToxicFrog/doom-mods/releases/tag/gun-bonsai-0.9.7).
