### ISSUE TITLE
[Bug] GunBonsai: Some translation strings are not translated

### ISSUE THREAD

**Issue by Blueberryy** [ToxicFrog/doom-mods#18]
(i'm using 0.10 version)
"Lv.", "Level" and "XP" are not translated for some reason but they translated in file.

Also, softcap ``s`` and radius ``m`` should be added to the file too

And ``TFLV_Upgrade_Shield_TT``, ``TFLV_Upgrade_Submunitions_TT`` strings formatted text like **@shortrange** is not coverting into numbers.

**Comment by ToxicFrog** [comment]
The formatted text for those is working fine for me in both en and ru language modes. "Level", "Lv", and "XP" are also translating into "-й уровень", "Ур", and "опыта" respectively.

Keeping the bug open to track addition of s (seconds) and m (meters) to the language files.

**Comment by ToxicFrog** [comment]
Fixed in 204f694854e53749530ba307af34ac9db00b8d53

**Comment by Blueberryy** [comment]
> The formatted text for those is working fine for me in both en and ru language modes. "Level", "Lv", and "XP" are also translating into "-й уровень", "Ур", and "опыта" respectively.

Weird, it stays in english for me but weapon status is translated

**Comment by Blueberryy** [comment]
> > The formatted text for those is working fine for me in both en and ru language modes. "Level", "Lv", and "XP" are also translating into "-й уровень", "Ур", and "опыта" respectively.
> 
> Weird, it stays in english for me but weapon status is translated

Ah nvm. I had to reinstall the mod and now it works
