### ISSUE TITLE
[Bug] Adventures of Square (Square-Ware) Crashes while Loading

### ISSUE THREAD

**Issue by kinker31** [ToxicFrog/doom-mods#21]
## Files Used
(on GZDoom 4.10, launched with ZDL 3-1.1)
* square.pk3
* square1_wide.wad
* GunBonsai-0.10.1.pk3
## The Error Itself
```
R_InstallSpriteLump: Bad frame characters in lump CIRCLEHU
Execution could not continue.

R_InstallSprite: Sprite CIRC frame L is missing rotations
```

**Comment by ToxicFrog** [comment]
Fixed in 40b86f44bbae3b9ed76bf19b88b572808c2934d8. Sorry for the delay.
