### ISSUE TITLE
Latest Gun Bonsai mod doesn't work on LZDoom

### ISSUE THREAD

**Issue by jankespro12** [ToxicFrog/doom-mods#8]
I have a problem, for some reason Latest Gun Bonsai version doesn't work on LZDoom. Can you please fix it?

**Comment by ToxicFrog** [comment]
"Doesn't work" how? Does it fail to load, loads but immediately vmaborts, loads and runs but the gameplay is broken, other?

In general, when filing a bug report, it helps if you can provide:
- what you did (which in the case of doom mods includes mod load order, command line flags like `-warp`, etc
- what happened (including error messages, if any)
- what should have happened instead

**Comment by jankespro12** [comment]
Well, look at this log
LZDoom version 3.88a
OS: Windows 10 (or higher) (NT 10.0) Build 19044
    
M_LoadDefaults: Load system defaults.
Using program directory for storage
W_Init: Init WADfiles.
 adding D:/Gry/LZDoom/lzdoom.pk3, 713 lumps
 adding D:/Gry/LZDoom/game_support.pk3, 291 lumps
 adding ./doom_complete.pk3, 3277 lumps
 adding D:/Gry/LZDoom/lights.pk3, 6 lumps
 adding D:/Gry/LZDoom/brightmaps.pk3, 499 lumps
 adding D:/Gry/LZDoom/game_widescreen_gfx.pk3, 119 lumps
 adding D:/Gry/LZDoom/skins/beavbuttdash.wad, 361 lumps
 adding D:/Gry/LZDoom/skins/DoomMetalVol5.wad, 80 lumps
 adding D:/Gry/LZDoom/skins/DOOMTEST.wad, 15 lumps
 adding D:/Gry/LZDoom/skins/pk_doom_sfx_20120224.wad, 77 lumps
 adding D:/Gry/LZDoom/skins/SKYDIVE.wad, 8 lumps
 adding D:/Gry/LZDoom/skins/smk4simpledecals.wad, 12 lumps
 adding libtooltipmenu-0.2.1.pk3, 6 lumps
 adding GunBonsai-0.9.2.pk3, 235 lumps
I_Init: Setting up machine state.
CPU speed: 2904 MHz
CPU Vendor ID: GenuineIntel
  Name: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
  Family 6, Model 165, Stepping 3
  Features: MMX SSE SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 HyperThreading
Renderer: OpenGL
V_Init: allocate screen.
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
  Opened device OpenAL Soft on Głośniki (Realtek(R) Audio)
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
Invalid data encountered for texture GunBonsai-0.9.2.pk3:sprites/ui/.gitignore
Invalid data encountered for texture GunBonsai-0.9.2.pk3:sprites/ui/hud.xcf
Invalid data encountered for texture GunBonsai-0.9.2.pk3:sprites/ui/makefile
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
Script error, "GunBonsai-0.9.2.pk3:ca.ancilla.bonsai/eventhandler.zsc" line 36:
Unknown identifier 'nextmap'
Script warning, "GunBonsai-0.9.2.pk3:ca.ancilla.bonsai/weaponinfo.zsc" line 61:
Incorrect number of return values. Got 1, but expected 0
Script warning, "GunBonsai-0.9.2.pk3:ca.ancilla.bonsai/weaponinfo.zsc" line 64:
Incorrect number of return values. Got 1, but expected 0

Execution could not continue.

1 errors while parsing DECORATE scripts

**Comment by jankespro12** [comment]
When it loads, it's just a script error

**Comment by ToxicFrog** [comment]
That looks like lzDoom might not support the `WorldEvent.nextmap` field, which could be a problem. I'll poke at it over the weekend -- I really don't want to have to drop lzDoom support, but there's a lot of recent zscript APIs it doesn't support. :/

**Comment by ToxicFrog** [comment]
Needs more testing, but I may have a workaround -- using `level.totaltime` as a proxy for whether a new game has been started (vs. a normal level transition).

**Comment by ToxicFrog** [comment]
Fixed in edd214d0497a2b71d96e48b0cb1829bbdcb355fd and will be in the next release.
